# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  username: root
  password: root
  host:     localhost
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: baa


default: &default
  adapter: mysql2
  database: <%=ENV['OPENSHIFT_APP_NAME']%>
  username: <%=ENV['OPENSHIFT_MYSQL_DB_USERNAME']%>
  password: <%=ENV['OPENSHIFT_MYSQL_DB_PASSWORD']%>
  host:     <%=ENV['OPENSHIFT_MYSQL_DB_HOST']%>
  port:     <%=ENV['OPENSHIFT_MYSQL_DB_PORT']%> 
  adapter: mysql2
  encoding: utf8
  pool: 5

test:
  <<: *default
  database: baa_test

production:
  <<: *default
  database: baa
